# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import transcription_pb2 as transcription__pb2


class AudioTranscriptionStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TranscribeAudio = channel.stream_stream(
                '/sigper.transcription.AudioTranscription/TranscribeAudio',
                request_serializer=transcription__pb2.AudioSegmentRequest.SerializeToString,
                response_deserializer=transcription__pb2.TranscriptResponse.FromString,
                )


class AudioTranscriptionServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TranscribeAudio(self, request_iterator, context):
        """Method for bidirectional stream transcription of audio
        Sends audio binary data (16Khz mono PCM) and receives transcript back
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioTranscriptionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TranscribeAudio': grpc.stream_stream_rpc_method_handler(
                    servicer.TranscribeAudio,
                    request_deserializer=transcription__pb2.AudioSegmentRequest.FromString,
                    response_serializer=transcription__pb2.TranscriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sigper.transcription.AudioTranscription', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AudioTranscription(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TranscribeAudio(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/sigper.transcription.AudioTranscription/TranscribeAudio',
            transcription__pb2.AudioSegmentRequest.SerializeToString,
            transcription__pb2.TranscriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
